### ISSUE TITLE
Update LESS version to avoid old graceful-fs

### ISSUE THREAD

**Issue by colinbate** [brunch/less-brunch#32]
If we update to LESS 2.6.1 it will reference a newer version of `graceful-fs` which works properly with newer node versions.

**Comment by hgwood** [comment]
@paulmillr :warning: less-brunch will not work under Node 7 if the less dependency is not updated. Node 7 should be released next month.

**Comment by paulmillr** [comment]
@hgwood feel free to submit a pull request.

**Comment by hgwood** [comment]
Sure :)

**Comment by hgwood** [comment]
See #34.

**Comment by hgwood** [comment]
Also, I'm sorry if my message made you feel pressured. I only wanted to make you aware of the problem in case you were not. The reason I did not make a PR straight away is that the change was so small I thought you wouldn't have bothered with one.
