### ISSUE TITLE
npm less packages question

### ISSUE THREAD

**Issue by laduke** [brunch/less-brunch#33]
Hi,
I don't know what I'm doing. I installed bootstrap@3 with npm into my brunch project. 

I feel like I should be able to put something like

```
        less: {
            paths: ["node_modules/bootstrap/less/"],
```

in brunch-config and something like 

`@import "bootstrap"`
in app.less

brunch build -v doesn't list the node_modules path I set above. 
If I put the full path to bootstrap after @import, that works (doesn't seem right though).

I tried a few other brunch skeletons that use bootstrap, but they we're all using bower if I remember correctly.  

I'm just looking for the simplest way to get bootstrap going with like:

```
brunch new test -s es6
npm install --save bootstrap@3
```

**Comment by paulmillr** [comment]
No such an easy UI for now. We're working on it.
