### ISSUE TITLE
Infinite loop in v2.8.0

### ISSUE THREAD

**Issue by colinbate** [brunch/less-brunch#44]
With the release of less-brunch 2.8.0, this plugin is now breaking my builds. Or I should say, sending them into an infinite loop of some sort.

We had a build take 50+ minutes just outputting `LESSCompiler is taking long to process` every 15 seconds. We had to kill it manually.

I will try to create a sample that reproduces this as soon as I can, but I wanted to create the issue in case there was an obvious reason this was happening.

**Comment by denysdovhan** [comment]
Hi, @colinbate! I'm trying to figure out what is the cause of problem.

> I will try to create a sample that reproduces this as soon as I can,…

That would help me a lot.

**Comment by colinbate** [comment]
https://github.com/colinbate/brunch-angular-testing-issue/tree/less-brunch-44

The `less-brunch-44` branch on https://github.com/colinbate/brunch-angular-testing-issue if you are cloning. However, I will say that this only appears to happen with an older version of Brunch (2.8.2 is the one I tried). So you may feel this isn't a real issue, it may be worth understanding. Some people pin their `brunch` version due to stability issues.

**Comment by shvaikalesh** [comment]
Hey @colinbate. Pin `less-brunch` to `~2.7` then.

**Comment by colinbate** [comment]
Yes, that was what I did. My setup is fine at the moment.

**Comment by denysdovhan** [comment]
@colinbate, try to build your project with plugin's version from `fix-44` branch:

```
"less-brunch": "brunch/less-brunch#fix-44"
```

**Comment by colinbate** [comment]
The branch is gone, but I see 2.8.1 is out, and using that seems to work. Thanks.

**Comment by denysdovhan** [comment]
👍🏻
